// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// SPDX-License-Identifier: GPL-2.0-or-later

package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AppPage is tally's local-first app shell (epic #1). It renders only the static
// chrome — the Amber CRT top bar, command line, and status ticker — plus an
// empty <main> mount point and a <noscript> fallback. Everything else (the
// tally list, detail views, and all persistence) is driven client-side by
// static/app.js against browser IndexedDB: no server, no data layer here. The
// same export feeds GitHub Pages, so the published site is the whole app.
func AppPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"color-scheme\" content=\"dark\"><meta name=\"theme-color\" content=\"#100F0D\"><title>tally</title><meta name=\"description\" content=\"tally — a local-first container for notes, checklists, and reminders.\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"static/favicon.svg\"><link rel=\"stylesheet\" href=\"static/app.css\"><script src=\"static/app.js\" defer></script></head><body><div class=\"crt-beam\" aria-hidden=\"true\"></div><div class=\"app\"><header class=\"topbar\"><a class=\"brand\" href=\"./\"><span class=\"tally-mark\" aria-hidden=\"true\"><span></span><span></span><span></span><span></span><span class=\"slash\"></span></span> tally</a> <span class=\"version\" title=\"running build\"><span class=\"dot\" aria-hidden=\"true\"></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(versionString())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/app.templ`, Line: 33, Col: 110}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></header><div class=\"cmdline\" aria-hidden=\"true\"><span class=\"prompt\">tally&gt;</span> <span class=\"cmd\">NCH</span> <span class=\"go\">GO</span> <span class=\"caret\"></span></div><div class=\"ticker\" id=\"ticker\" role=\"status\" aria-label=\"status\"><span class=\"stat\">NOTCHES <b>0</b></span></div><main id=\"view\" aria-live=\"polite\"></main><noscript><p class=\"lede\" style=\"padding:var(--sp-4)\">tally is a local-first app — it needs JavaScript enabled to run. Your data stays in this browser.</p></noscript><footer class=\"foot\">tally — local-first · data stays in your browser</footer></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
